# Create a linked clone VM from a template in Proxmox VE
# and assign it a cloud-init user and password
# returns the VM ID and IP address username and password

---
- name: >
    Create linked clone VM from template in Proxmox VE.
    The VM source is Rocky10-Template.
    The target VM name is Rocky-cloud-img-ansible-{vmid}
# Can run on local host because it uses the proxmox api
  hosts: localhost
#  vars_prompt:
    # - name: newid_user
    #   prompt: "ID for the new VM? (Leave blank for next available ID): "
    #   private: false

    # - name: vm_name
    #   prompt: "Name for the new VM: "
    #   private: false
    #   default: "Rocky-cloud-img-ansible"

  vars:
    proxmox_var_file: "inventory/host_vars/proxmox01.yml"
    proxmox_vault_file: "inventory/host_vars/proxmox01.vault"

    # VM parameters -- name will be appended with id
    vm_name: "rocky-cloud-img-ansible"
    vm_pass: "Kode1234!"
    vm_user: "root"
    vm_template: "Rocky10-Template"
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGcYHIt6X4pr5xSDkiy3EpJPn/WP+JGW84bdrYnVyO0S"

  tasks:
    - name: Include vars of proxmox
      ansible.builtin.include_vars:
        file: "{{ proxmox_var_file }}"
        name: proxmox

    - name: Include vault vars of proxmox
      ansible.builtin.include_vars:
        file: "{{ proxmox_vault_file }}"

    - name: Create linked clone VM from template
      community.proxmox.proxmox_kvm:
        node: "{{ proxmox.node }}"
        # when full is false and format is unspecified, a linked clone is created
        full: false
        format: unspecified
        timeout: 500
        clone: "{{ vm_template }}"
        name: "{{ vm_name }}"
        # newid: "{{ newid }}"
      register: new_vm_id
      environment: "{{ proxmox.env }}"
      # ignore_errors: {{ ansible_check_mode }}


    - name: Set the newid and vm_name facts
      ansible.builtin.set_fact:
        newid: "{{ new_vm_id.vmid }}"
        vm_name: "{{ vm_name }}-{{ new_vm_id.vmid }}"


    - name: Update VM configuration to add cloud init device
      community.proxmox.proxmox_kvm:
        node: "{{ proxmox.node }}"
        vmid: "{{ newid }}"
        # add cloud init device
        ide:
          ide2: 'local-lvm:cloudinit,format=raw'
        # cloud-init settings
        ciuser: "{{ vm_user }}"
        cipassword: "{{ vm_pass }}"
        sshkeys: "{{ ssh_key }}"
        # rename the vm to include the vmid
        name: "{{ vm_name }}"
        update: true
      register: result
      environment: "{{ proxmox.env }}"
      until: result is succeeded
      retries: 3
      delay: 5


    - name: Start the new VM
      community.proxmox.proxmox_kvm:
        node: "{{ proxmox.node }}"
        vmid: "{{ newid }}"
        state: started
      environment: "{{ proxmox.env }}"

    - name: Retrieve IP address of the new VM
      community.proxmox.proxmox_vm_info:
        node: "{{ proxmox.node }}"
        vmid: "{{ newid }}"
        network: true
        type: qemu
      register: vm_info
      until: vm_info.proxmox_vms[0].network[1]['ip-addresses'][0]['ip-address'] is defined
      retries: 5
      delay: 5
      environment: "{{ proxmox.env }}"

    - name: Set IP address fact
      ansible.builtin.set_fact:
        vm_ip_address: "{{ vm_info.proxmox_vms[0].network[1]['ip-addresses'][0]['ip-address'] }}"

    - name: Save VM details to a file
      ansible.builtin.copy:
        dest: "/workspaces/Ansible_learning/inventory/host_vars/{{ vm_name }}.yml"
        content: |
          ansible_host: {{ vm_ip_address }}
          ansible_user: {{ vm_user }}
          ansible_password: {{ vm_pass }}
          ansible_become_pass: {{ vm_pass }}
          server_name: {{ vm_name }}
          proxmox_vm_id: {{ newid }}
          proxmox_vm_name: {{ vm_name }}
        mode: "640"

    - name: Insert new host into inventory file
      ansible.builtin.blockinfile:
        path: "/workspaces/Ansible_learning/inventory/cloud-hosts.yml"
        block: |
          "        {{ vm_name }}:"
        state: present
        insertafter: |
          "  rocky-cloud:"
          "    hosts:"

    - name: Display the VM information
      ansible.builtin.debug:
        msg:
          - "VM ID: {{ newid }}"
          - "IP address: {{ vm_ip_address }}"
          - "Username: {{ vm_user }}"
          - "Password: {{ vm_pass }}"
