---
- name: Update the system using DNF
  hosts: "{{ kjhh | default('all') }}"
  become: true

  tasks:
    - name: debug
      ansible.builtin.debug:
        msg: "Updating the system using DNF on {{ kjhh }}"
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
        update_only: true
