ansible_host: 10.101.162.51
ansible_user: root
ansible_password: Kode1234!
ansible_become_pass: Kode1234!
server_name: rocky-cloud-img-ansible-104
proxmox_vm_id: 104
proxmox_vm_name: rocky-cloud-img-ansible-104
