ansible_host: 10.101.214.155
ansible_user: root
ansible_password: Kode1234!
ansible_become_pass: Kode1234!
server_name: rocky-cloud-img-ansible-103
proxmox_vm_id: 103
proxmox_vm_name: rocky-cloud-img-ansible-103
