---
all:
  hosts:
    rocky01:
    test01:
    proxmox01:


  children:
    web_servers:
      hosts:
        rocky01:

    db_servers:
      hosts:

    test:
      hosts:

    rocky_linux:
      hosts:
        rocky01:


    rocky_cloud:
      hosts:

