---
all:
  hosts:
    rocky01:
    test01:
    proxmox01:


  children:
    web_servers:
      hosts:
        rocky01:

    db_servers:
      hosts:

    test:
      hosts:

    rocky_linux:
      hosts:
        rocky01:


    rocky_cloud:
      hosts:

# # rocky-cloud-img-ansible-104 host marker begin ANSIBLE MANAGED BLOCK
        rocky-cloud-img-ansible-104:
# # rocky-cloud-img-ansible-104 host marker end ANSIBLE MANAGED BLOCK
